# Name of the workflow
name: Generate Snake Animation

# Controls when the action will run
on:
  # Run on a schedule (e.g., once a day at midnight)
  schedule:
    - cron: '0 0 * * *'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Step 1: Check out this repository's code
      - uses: actions/checkout@v4

      # Step 2: Generate the snake animation SVG
      - name: Generate Snake Animation
        uses: platane/snk@v3
        with:
          # Your GitHub username. This is the only required input.
          github_user_name: BBCnewslondon
          
          # A list of SVG output files to generate.
          # The file name is your choice, but 'dist' is a common directory for generated files.
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            
        env:
          # A GitHub personal access token is required to read your contribution graph.
          # The GITHUB_TOKEN is automatically created by Actions.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Commit and push the generated SVG file to the repository
      - name: Push Snake Animation
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update snake animation"
          file_pattern: dist/*.svg
